[build]
#target = 'x86_64-pc-windows-gnu'
#target = 'x86_64-unknown-linux-gnu'
#target = 'x86_64-apple-darwin'

#[target.x86_64-apple-darwin]
#linker = "x86_64-apple-darwin14-clang"
#ar = "x86_64-apple-darwin14-ar"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=-crt-static"]
