# SPDX-FileCopyrightText: 2022 Empo Inc.
#
# SPDX-License-Identifier: CC0-1.0

name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.targets[0] }}
    strategy:
      matrix:
        targets:
          - [ubuntu-latest, [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]]
          - [windows-latest, [x86_64-pc-windows-msvc, aarch64-pc-windows-msvc]]
          - [macos-latest, [x86_64-apple-darwin, aarch64-apple-darwin]]
        clang: [["13.0", "clang_13_0"]]
    env:
      RUSTFLAGS: "-C target-feature=-crt-static"
    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ matrix.clang[0] }}
          directory: ${{ runner.temp }}/llvm-${{ matrix.clang[0] }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.targets[1][1] }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - name:  Install libraries
        run:   |
               if [ "$RUNNER_OS" == "Linux" ]; then
                    sudo ./ci/ubuntu-multiarch.sh
                    sudo dpkg --add-architecture arm64
                    # Bust cache
                    sudo rm -rf /var/lib/apt/lists/*
                    sudo apt update
                    sudo apt install -y pkg-config libdbus-1-3 libdbus-1-dev libsystemd-dev libdbus-glib-1-dev libssl-dev
                    sudo apt install -y libdbus-1-3:arm64 libdbus-1-dev:arm64 libsystemd-dev:arm64 libdbus-glib-1-dev:arm64 libssl-dev:arm64
                    sudo apt install -y gcc-aarch64-linux-gnu libgcc-10-dev:arm64
               else
                    echo "This platform does not require libdbus."
               fi
        shell: bash
      - uses: Swatinem/rust-cache@v1
      - name: Unzip
        run:   |
               unzip windll.zip
        shell: bash
      - name: Build
        run:   |
               if [ "$RUNNER_OS" == "Linux" ]; then
                    export RUSTFLAGS='-C target-feature=-crt-static'
                    cargo build --release --target ${{ matrix.targets[1][0] }} --features dbus
                    export PKG_CONFIG=/usr/bin/aarch64-linux-gnu-pkg-config
                    cargo build --release --target ${{ matrix.targets[1][1] }} --features dbus
               elif [ "$RUNNER_OS" == "Windows" ]; then
                    rm -f ./netlink-request
                    rm -f ./wireguard-control
                    cp -rv ./innernet/netlink-request ./
                    cp -rv ./innernet/wireguard-control ./
                    export RUSTFLAGS='-C target-feature=+crt-static'
                    cargo build --release --target ${{ matrix.targets[1][0] }} --bin mareel-vpnd --bin vpnd-configgen
                    cargo build --release --target ${{ matrix.targets[1][1] }} --bin mareel-vpnd --bin vpnd-configgen
               else
                    export RUSTFLAGS='-C target-feature=+crt-static'
                    cargo build --release --target ${{ matrix.targets[1][0] }}
                    cargo build --release --target ${{ matrix.targets[1][1] }}
               fi
        shell: bash
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.targets[0] }}
          path: |
            target/**/release/mareel-vpnd
            target/**/release/mareel-vpnd.exe
            target/**/release/vpnd-configgen
            target/**/release/vpnd-configgen.exe
