name: release
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.targets[0] }}
    strategy:
      matrix:
        targets:
          - [ubuntu-latest, [x86_64-unknown-linux-gnu]]
          - [windows-latest, [x86_64-pc-windows-msvc, aarch64-pc-windows-msvc]]
          - [macos-latest, [x86_64-apple-darwin, aarch64-apple-darwin]]
        clang: [["13.0", "clang_13_0"]]
    env:
      RUSTFLAGS: "-C target-feature=+crt-static"
    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ matrix.clang[0] }}
          directory: ${{ runner.temp }}/llvm-${{ matrix.clang[0] }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release --target ${{ matrix.targets[1] }}
